# Pre-commit Hooks for Terraform
# Install: pip install pre-commit && pre-commit install

repos:
  # Terraform formatting and validation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
        name: Terraform Format
        description: Format Terraform files
        
      - id: terraform_validate
        name: Terraform Validate
        description: Validate Terraform configuration
        
      - id: terraform_docs
        name: Generate Terraform Docs
        description: Generate documentation
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          
      - id: terraform_tflint
        name: TFLint
        description: Lint Terraform files
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          
      - id: terraform_tfsec
        name: tfsec Security Scan
        description: Security scanning
        args:
          - --args=--config-file=__GIT_WORKING_DIR__/.tfsec.yml

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        
      - id: end-of-file-fixer
        name: Fix End of Files
        
      - id: check-yaml
        name: Check YAML syntax
        args: ['--unsafe']
        
      - id: check-added-large-files
        name: Check for Large Files
        args: ['--maxkb=1000']
        
      - id: check-merge-conflict
        name: Check for Merge Conflicts
        
      - id: detect-private-key
        name: Detect Private Keys
        
      - id: check-case-conflict
        name: Check Case Conflicts

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        name: Markdown Lint
        args: ['--fix']

  # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect Secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

